# Generated by Django 4.2 on 2023-04-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0003_alter_order_color_alter_order_size'),
        ('product_module', '0002_alter_productbrand_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
