# Generated by Django 4.2 on 2023-04-08 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0002_order_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue'), ('black', 'black'), ('white', 'white')], default='red', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
