# Generated by Django 4.2 on 2023-04-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_alter_productbrand_logo'),
        ('account_module', '0002_user_wish_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wish_list',
            field=models.ManyToManyField(blank=True, to='product_module.product'),
        ),
    ]
